import { useState, useEffect } from 'react'
import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const superHeroApi = `https://thronesapi.com/api/v2/Characters`;

export async function getServerSideProps() {
  const res = await fetch(superHeroApi);
  const data = await res.json();
  return {
    props: { data }
  }
}

export default function Home({ data }) {
  const [page, setPage] = useState({ start: 0, end: 4 })
  let characters = data.slice(page.start, page.end);
  characters.push({
    id: 123,
    fullName: 'Ser Bikram Karki',
    imageUrl: 'https://scontent.fhel1-1.fna.fbcdn.net/v/t1.18169-9/12246826_995719907136592_6493791260710503344_n.jpg?_nc_cat=110&ccb=1-3&_nc_sid=174925&_nc_ohc=5GKyxTrMoesAX_ZhNDD&_nc_oc=AQm1JPMEU4YhmY-BGGPCRyTqRTfvbBI2RBWkI22x6ufANdmEN6i9g-3y8trLIdVtlE75vyylSFu7H2fMAMwoYyIo&_nc_ht=scontent.fhel1-1.fna&oh=db62aa3e138c6d6e08cdc922a6084757&oe=6127E1E4',
    title: 'Lord of the Blue Seas, White Sky, Red Blood',
    family: 'House Chaudhary'
  },{
    id: 124,
    fullName: 'Lord Paulo the First',
    imageUrl: '/SerPaulo.jpg',
    title: "half the twin",
    family: 'House Blackfyre'
  })
  const [state, setState] = useState(characters)
  const onLoadMore = () => {
    setPage({ start: page.start + 4, end: page.end + 4 })
    setState([...state, ...data.slice(page.start, page.end)])
  }

  useEffect(() => {
    setPage({ start: page.start + 4, end: page.end + 4 })
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Game of Thrones Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Game of Thrones Characters
        </h1>
        <p className={styles.description}>
          <em>Winter is Coming</em>
        </p>
        <ul className={styles.grid}>
          {state.map(result => {
            const { id, fullName, imageUrl, title, family } = result;
            return (
              <li key={id} className={styles.card}>
                <a href="#">
                  <Image
                    placeholder="blur"
                    src={imageUrl}
                    alt={`${fullName}`}
                    width={200}
                    height={200}
                    blurDataURL={imageUrl}
                    loading="lazy"
                  />
                  <h5><em>{title}</em></h5>
                  <h3>{fullName}</h3>
                  <h6>{family}</h6>
                </a>
              </li>
            )
          })}
        </ul>
        <p>
          <h5 className={styles.loadmore} onClick={onLoadMore}>Load More</h5>
        </p>
      </main>
      <footer className={styles.footer}>
        &copy; Marco 2021
      </footer>
    </div>
  )
}
